# Generated by Django 4.1.3 on 2022-12-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0003_alter_producto_fecha_remito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_remito',
            new_name='fecha_de_solicitud',
        ),
    ]
