# Generated by Django 4.1.3 on 2022-12-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0004_rename_fecha_remito_producto_fecha_de_solicitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('monto', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ventas', models.CharField(max_length=40)),
                ('monto_recaudado', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_de_solicitud',
            new_name='fecha_de_ingreso',
        ),
    ]
