# Generated by Django 4.1.3 on 2022-12-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0005_comprador_ventas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha_de_venta',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
