# Generated by Django 4.1.3 on 2022-12-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0006_ventas_fecha_de_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprador',
            old_name='monto',
            new_name='direccion',
        ),
    ]
