# Generated by Django 4.1.3 on 2022-12-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0008_alter_ventas_fecha_de_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
