# Generated by Django 4.1.3 on 2022-12-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0009_delete_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ventas', models.CharField(max_length=40)),
                ('monto_recaudado', models.IntegerField()),
                ('fecha_de_venta', models.DateField()),
            ],
        ),
    ]
