# Generated by Django 4.1.3 on 2022-12-26 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0010_ventas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventas',
            old_name='total_ventas',
            new_name='cantidad_ventas',
        ),
    ]
