# Generated by Django 4.1.3 on 2022-12-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0011_rename_total_ventas_ventas_cantidad_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_de_venta',
            field=models.CharField(max_length=40),
        ),
    ]
