# Generated by Django 4.1.3 on 2022-12-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0013_alter_ventas_fecha_de_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha_de_venta',
            field=models.CharField(max_length=40),
        ),
    ]
