# Generated by Django 4.1.3 on 2022-12-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMaturano', '0014_alter_ventas_fecha_de_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='direccion',
            field=models.CharField(max_length=40),
        ),
    ]
